### ISSUE TITLE
Zephyr version

### ISSUE THREAD

**Issue by arfoll** [01org/CODK-Z#23]
Hi CODK dev team. Any plans to update to zephyr v1.5+?

**Comment by eriknyquist** [comment]
It's already happened!
https://github.com/01org/zephyr/commit/5ca45ba3f2469cd859fac3a448a17158bbb47866

**Comment by calvinatintel** [comment]
Nupe, that commit was for M. I'll do it for Z shortly.

**Comment by arfoll** [comment]
Cool thanks!

**Comment by kitsunami** [comment]
This has happened !
